
(* 4x4 ff... *)

(*use "/home/nic/project/prelude/pervasives.ML";*)
use "/home/nic/project/prelude/PREL.ML";
use "/home/nic/project/prelude/SORT.ML";
use "/home/nic/project/prelude/QLAYOUT.ML";
use "/home/nic/project/prelude/MISCLAY.ML";
use "/home/nic/project/prelude/PAR3.ML";
use "/home/nic/project/prelude/IMP_HASH.ML";

use "ff-setup.ML";

use "/home/nic/project/stack4x4/book.ML";
use "/home/nic/project/stack4x4/force.ML";

